---
title: "argonDash::argonInfoCard"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(argonDash)
```


Create a Boostrap 4 dashboard info card
#### Description
Build an argon dashboard info card

#### Usage
<pre><code>

argonInfoCard(value, title = NULL, stat = NULL, stat_icon = NULL,
description = NULL, icon, icon_background = NULL,
hover_lift = FALSE, shadow = FALSE, background_color = NULL,
gradient = FALSE, width = 3)

</code></pre>
#### Arguments

* ``value``: info card value.
* title info card title.
* ``stat info``:  card stat value.
* stat_icon info card stat icon.
description info card stat description.
icon
info card icon.
icon_background
info card icon background color.10
argonSidebarHeader
* ``hover_lift``: Whether to apply a lift effect on hover. FALSE by default. Not compatible with
floating.
shadow Whether to apply a shadow effect. FALSE by default.
* background_color Card background color. NULL by default.
* gradient Whether to apply a gradient effect on the card background. FALSE by default.
* width info card width. Between 1 and 12.

#### Author(s)
David Granjon, <dgranjon@ymail.com>
