languages_section
Languages Section of ISS

#### Description

RInno currently supports 25 languages. Check the languages directory of Inno Setup for a com-
plete list, and see [Languages] section for details.

#### Usage
<pre><code>

languages_section(iss, language = "english")

</code></pre>
#### Arguments

iss Character vector which cumulatively becomes an Inno Setup Script (ISS).
language Character vector of lower case languages to include.
Value
Chainable character vector, which can be used as the text argument of writeLines to generate an
ISS.
Author(s)
Jonathan M. Hill20
run_section
nativefy_app
Package app into electron with nativefier

#### Description

Package app into electron with nativefier

#### Usage
<pre><code>

nativefy_app(app_name, app_dir, nativefier_opts,
app_icon = "default.ico")

</code></pre>
#### Arguments

app_name
The name of the app. It will be displayed throughout the installer’s window
titles, wizard pages, and dialog boxes. See [Setup]:AppName for details. For
continuous installations, app_name is used to check for an R package of the same
name, and update it. The Continuous Installation vignette has more details.
app_dir
Development app’s directory, defaults to getwd().
nativefier_opts
Character vector. Extra options to pass to nativefier when user_browser = "electron".
Each string in the vector should be a valid nativefier command. For example,
c('--no-overwrite', '--conceal', '--show-menu-bar'). For more in-
formation, system("nativefier --help").
app_icon
</code></pre>
