Package ‘shinyWidgets’
November 5, 2018
Title Custom Inputs Widgets for Shiny
Version 0.4.4

#### Description
 Some custom inputs widgets to use in Shiny applications, like a toggle switch to re-
place checkboxes. And other components to pimp your apps.
URL https://github.com/dreamRs/shinyWidgets
BugReports https://github.com/dreamRs/shinyWidgets/issues
Depends R (>= 3.1.0)
Imports shiny (>= 0.14), htmltools, jsonlite, grDevices, scales
License GPL-3 | file LICENSE
Encoding UTF-8
LazyData true
RoxygenNote 6.1.0
Suggests shinydashboard, viridisLite, RColorBrewer, testthat, covr,
shinydashboardPlus
NeedsCompilation no
Author Victor Perrier [aut, cre],
Fanny Meyer [aut],
David Granjon [aut] (jQuery Knob shiny interface & sliders appearance),
SnapAppointments [cph] (bootstrap-select),
Mattia Larentis [ctb, cph] (Bootstrap Switch),
Emanuele Marchi [ctb, cph] (Bootstrap Switch),
Mark Otto [ctb] (Bootstrap library),
Jacob Thornton [ctb] (Bootstrap library),
Bootstrap contributors [ctb] (Bootstrap library),
Twitter, Inc [cph] (Bootstrap library),
Flatlogic [cph] (Awesome Bootstrap Checkbox),
mouse0270 [ctb, cph] (Material Design Switch),
Tristan Edwards [ctb, cph] (SweetAlert),
Fabian Lindfors [ctb, cph] (multi.js),
Anthony Terrien [ctb, cph] (jQuery Knob),
Daniel Eden [ctb, cph] (animate.css),
1R topics documented:
2
Ganapati V S [ctb, cph] (bttn.css),
Brian Grinstead [ctb, cph] (Spectrum),
Lokesh Rajendran [ctb, cph] (pretty-checkbox),
Leon Gersen [ctb, cph] (wnumb & noUiSlider),
Timofey Marochkin [ctb, cph] (air-datepicker),
Tobias Ahlin [ctb, cph] (CSS spin)
Maintainer Victor Perrier <victor.perrier@dreamrs.fr>
Repository CRAN
Date/Publication 2018-11-05 12:00:03 UTC
R topics documented:
actionBttn . . . . . . . .
actionGroupButtons . . .
addSpinner . . . . . . .
airDatepicker . . . . . .
animateOptions . . . . .
animations . . . . . . . .
awesomeCheckbox . . .
awesomeCheckboxGroup
awesomeRadio . . . . .
checkboxGroupButtons .
chooseSliderSkin . . . .
circleButton . . . . . . .
closeSweetAlert . . . . .
colorSelectorInput . . . .
confirmSweetAlert . . .
demoAirDatepicker . . .
demoNoUiSlider . . . .
downloadBttn . . . . . .
dropdown . . . . . . . .
dropdownButton . . . .
inputSweetAlert . . . . .
knobInput . . . . . . . .
materialSwitch . . . . .
multiInput . . . . . . . .
noUiSliderInput . . . . .
panel . . . . . . . . . . .
pickerGroup-module . .
pickerInput . . . . . . .
pickerOptions . . . . . .
prettyCheckbox . . . . .
prettyCheckboxGroup . .
prettyRadioButtons . . .
prettySwitch . . . . . . .
prettyToggle . . . . . . .
progress-bar . . . . . . 






































































































































































































8
11
12
13
14
15
17
18
20
20
21
22
25
26
27
28
30
32
33
35
36
38
41
42
44
48
51
55
57
60
62
65R topics documented:
progressSweetAlert . . . . . . .
radioGroupButtons . . . . . . .
searchInput . . . . . . . . . . .
selectizeGroup-module . . . . .
sendSweetAlert . . . . . . . . .
setBackgroundColor . . . . . .
setBackgroundImage . . . . . .
setShadow . . . . . . . . . . . .
setSliderColor . . . . . . . . . .
shinyWidgets . . . . . . . . . .
shinyWidgetsGallery . . . . . .
sliderTextInput . . . . . . . . .
spectrumInput . . . . . . . . . .
switchInput . . . . . . . . . . .
textInputAddon . . . . . . . . .
toggleDropdownButton . . . . .
tooltipOptions . . . . . . . . . .
updateAirDateInput . . . . . . .
updateAwesomeCheckbox . . .
updateAwesomeCheckboxGroup
updateAwesomeRadio . . . . .
updateCheckboxGroupButtons .
updateKnobInput . . . . . . . .
updateMaterialSwitch . . . . . .
updateMultiInput . . . . . . . .
updateNoUiSliderInput . . . . .
updatePickerInput . . . . . . . .
updatePrettyCheckbox . . . . .
updatePrettyCheckboxGroup . .
updatePrettyRadioButtons . . .
updatePrettySwitch . . . . . . .
updatePrettyToggle . . . . . . .
updateRadioGroupButtons . . .
updateSearchInput . . . . . . .
updateSliderTextInput . . . . . .
updateSpectrumInput . . . . . .
updateSwitchInput . . . . . . .
updateVerticalTabsetPanel . . .
useShinydashboard . . . . . . .
useShinydashboardPlus . . . . .
useSweetAlert . . . . . . . . . .
vertical-tab . . . . . . . . . . .
wNumbFormat . . . . . . . . .

actionBttn
actionBttn
Awesome action button

#### Description

Like actionButton but awesome, via https://bttn.surge.sh/

#### Usage
<pre><code>

actionBttn(inputId, label = NULL, icon = NULL, style = "unite",
color = "default", size = "md", block = FALSE, no_outline = TRUE)

</code></pre>
#### Arguments

* ``inputId``:   The input slot that will be used to access the value.
* label The contents of the button, usually a text label.
* icon An optional icon to appear on the button.
* style Style of the button, to choose between simple, bordered, minimal, stretch, jelly, gradient, fill, material-circle, material-flat, pill, float, unite.
* color Color of the button : default, primary, warning, danger, success, royal.
* ``size ``:  Size of the button : xs,sm, md, lg.
* block Logical, full width button.
* no_outline Logical, don’t show outline when navigating with keyboard/interact using mouse or touch.
See Also
downloadBttn

#### Examples
<pre><code>

## Not run:
if (interactive()) {
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
tags$h2("Awesome action button"),
tags$br(),
actionBttn(
inputId = "bttn1",
label = "Go!",
color = "primary",
style = "bordered"
),
tags$br(),actionGroupButtons
)
5
verbatimTextOutput(outputId = "res_bttn1"),
tags$br(),
actionBttn(
inputId = "bttn2",
label = "Go!",
color = "success",
style = "material-flat",
icon = icon("sliders"),
block = TRUE
),
tags$br(),
verbatimTextOutput(outputId = "res_bttn2")
server <- function(input, output, session) {
output$res_bttn1 <- renderPrint(input$bttn1)
output$res_bttn2 <- renderPrint(input$bttn2)
}
shinyApp(ui = ui, server = server)
}
## End(Not run)
</code></pre>





animations
Animation names

#### Description

List of all animations by categories

#### Usage
<pre><code>

animations
Format
A list of lists
Source
https://github.com/daneden/animate.css/blob/master/animate-config.jsonawesomeCheckbox
13


closeSweetAlert
Close Sweet Alert

#### Description

Close Sweet Alert

#### Usage
<pre><code>

closeSweetAlert(session)colorSelectorInput
21

</code></pre>
#### Arguments

session
The session object passed to function given to shinyServer.
confirmSweetAlert
Launch a confirmation dialog

#### Description

Launch a popup to ask confirmation to the user

#### Usage
<pre><code>

confirmSweetAlert(session, inputId, title = NULL, text = NULL,
type = NULL, danger_mode = FALSE, btn_labels = c("Cancel",
"Confirm"), closeOnClickOutside = FALSE, html = FALSE)

</code></pre>
#### Arguments

* ``session``:  The session object passed to function given to shinyServer.
* ``inputId``:   The input slot that will be used to access the value.
title Title of the alert.confirmSweetAlert
23
text Text of the alert, can contains HTML tags.
type Type of the alert : info, success, warning or error.
danger_mode Logical, activate danger mode (focus on cancel button).
btn_labels
Labels for buttons.
closeOnClickOutside
Decide whether the user should be able to dismiss the modal by clicking outside
of it, or not.
html
Does text contains HTML tags ?
See Also
sendSweetAlert, inputSweetAlert

#### Examples
<pre><code>

## Not run:
if (interactive()) {
library("shiny")
library("shinyWidgets")
ui <- fluidPage(
tags$h1("Confirm sweet alert"),
actionButton(
inputId = "launch",
label = "Launch confirmation dialog"
),
verbatimTextOutput(outputId = "res"),
uiOutput(outputId = "count")
)
server <- function(input, output, session) {
# Launch sweet alert confirmation
observeEvent(input$launch, {
confirmSweetAlert(
session = session,
inputId = "myconfirmation",
type = "warning",
title = "Want to confirm ?",
danger_mode = TRUE
)
})
# raw output
output$res <- renderPrint(input$myconfirmation)
# count click
true <- reactiveVal(0)24
confirmSweetAlert
}
false <- reactiveVal(0)
observeEvent(input$myconfirmation, {
if (isTRUE(input$myconfirmation)) {
x <- true() + 1
true(x)
} else {
x <- false() + 1
false(x)
}
}, ignoreNULL = TRUE)
output$count <- renderUI({
tags$span(
"Confirm:", tags$b(true()),
tags$br(),
"Cancel:", tags$b(false())
)
})
shinyApp(ui, server)
# other options :
ui <- fluidPage(
tags$h1("Confirm sweet alert"),
actionButton(
inputId = "launch1",
label = "Launch confirmation dialog (with danger mode)"
),
verbatimTextOutput(outputId = "res1"),
tags$br(),
actionButton(
inputId = "launch2",
label = "Launch confirmation dialog (with normal mode)"
),
verbatimTextOutput(outputId = "res2"),
tags$br(),
actionButton(
inputId = "launch3",
label = "Launch confirmation dialog (with HTML)"
),
verbatimTextOutput(outputId = "res3")
)
server <- function(input, output, session) {
observeEvent(input$launch1, {
confirmSweetAlert(
session = session,
inputId = "myconfirmation1",demoAirDatepicker
25
type = "warning",
title = "Want to confirm ?",
danger_mode = TRUE
)
})
output$res1 <- renderPrint(input$myconfirmation1)
observeEvent(input$launch2, {
confirmSweetAlert(
session = session,
inputId = "myconfirmation2",
type = "warning",
title = "Are you sure ??",
btn_labels = c("Nope", "Yep"),
danger_mode = FALSE
)
})
output$res2 <- renderPrint(input$myconfirmation2)
observeEvent(input$launch3, {
confirmSweetAlert(
session = session,
inputId = "myconfirmation3",
title = NULL,
text = tags$b(
icon("file"),
"Do you really want to delete this file ?",
style = "color: #FA5858;"
),
btn_labels = c("Cancel", "Delete file"),
danger_mode = TRUE, html = TRUE
)
})
output$res3 <- renderPrint(input$myconfirmation3)
}
shinyApp(ui = ui, server = server)
}
## End(Not run)


demoNoUiSlider
Some examples on how to use noUiSliderInput

#### Description

Some examples on how to use noUiSliderInput

#### Usage
<pre><code>

demoNoUiSlider(example = "color")

</code></pre>
#### Arguments

example
Name of the example : "color", "update", "behaviour", "more", "format".

#### Examples
<pre><code>

## Not run:
if (interactive()) {
demoNoUiSlider("color")
}
## End(Not run)downloadBttn
27
downloadBttn
Create a download bttn

#### Description

Create a download button with actionBttn.

#### Usage
<pre><code>

downloadBttn(outputId, label = "Download", style = "unite",
color = "default", size = "md", block = FALSE, no_outline = TRUE)

</code></pre>
#### Arguments

outputId The name of the output slot that the downloadHandler is assigned to.
label The label that should appear on the button.
style Style of the button, to choose between simple, bordered, minimal, stretch,
jelly, gradient, fill, material-circle, material-flat, pill, float, unite.
color Color of the button : default, primary, warning, danger, success, royal.
* ``size ``:  Size of the button : xs,sm, md, lg.
block Logical, full width button.
no_outline Logical, don’t show outline when navigating with keyboard/interact using mouse
or touch.

#### Examples
<pre><code>

## Not run:
if (interactive()) {
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
tags$h2("Download bttn"),
downloadBttn(
outputId = "downloadData",
style = "bordered",
color = "primary"
)
)
server <- function(input, output, session) {
output$downloadData <- downloadHandler(
filename = function() {
paste('data-', Sys.Date(), '.csv', sep='')28
dropdown
)
},
content = function(con) {
write.csv(mtcars, con)
}
}
shinyApp(ui, server)
}
## End(Not run)


shinyWidgets
shinyWidgets: Custom inputs widgets for Shiny.

#### Description

The shinyWidgets package provides several custom widgets to extend those available in package
shiny

#### Examples
<pre><code>

## Not run:
if (interactive()) {
shinyWidgets::shinyWidgetsGallery()
}
## End(Not run)



updatePrettyCheckboxGroup
Change the value of a pretty checkbox on the client
107108










wNumbFormat
Format numbers in noUiSliderInput

#### Description

Format numbers in noUiSliderInputwNumbFormat
135

#### Usage
<pre><code>

wNumbFormat(decimals = NULL, mark = NULL, thousand = NULL,
prefix = NULL, suffix = NULL, negative = NULL)

</code></pre>
#### Arguments

decimals The number of decimals to include in the result. Limited to 7.
mark The decimal separator. Defaults to '.' if thousand isn’t already set to '.'.
thousand Separator for large numbers. For example: ' ' would result in a formatted
number of 1 000 000.
prefix A string to prepend to the number. Use cases include prefixing with money
symbols such as '$' or ''.
suffix A number to append to a number. For example: ',-'.
negative The prefix for negative values. Defaults to '-'.

#### Value

a named list.
Note
Performed via wNumb JavaScript library : https://refreshless.com/wnumb/.

#### Examples
<pre><code>

## Not run:
if (interactive()) {
library( shiny )
library( shinyWidgets )
ui <- fluidPage(
tags$h3("Format numbers"),
tags$br(),
noUiSliderInput(
inputId = "form1",
min = 0, max = 10000,
value = 800,
format = wNumbFormat(decimals = 3,
thousand = ".",
suffix = " (US $)")
),
verbatimTextOutput(outputId = "res1"),
tags$br(),
noUiSliderInput(136
wNumbFormat
inputId = "form2",
min = 1988, max = 2018,
value = 1988,
format = wNumbFormat(decimals = 0,
thousand = "",
prefix = "Year: ")
),
verbatimTextOutput(outputId = "res2"),
tags$br()
)
server <- function(input, output, session) {
output$res1 <- renderPrint(input$form1)
output$res2 <- renderPrint(input$form2)
}
shinyApp(ui, server)
}
## End(Not run)Index
noUiSliderInput, 38
∗Topic datasets
animations, 12
panel, 41
pickerGroup-module, 42
pickerGroupServer (pickerGroup-module),
42
pickerGroupUI (pickerGroup-module), 42
pickerInput, 43, 44, 105
pickerOptions, 44, 48
prettyCheckbox, 51
prettyCheckboxGroup, 55, 108
prettyRadioButtons, 57, 110
prettySwitch, 52, 60
prettyToggle, 52, 62
progress-bar, 65
progressBar (progress-bar), 65
progressSweetAlert, 66, 67
actionBttn, 4, 27, 29
actionGroupButtons, 5
addSpinner, 6
airDatepicker, 8
airDatepickerInput (airDatepicker), 8
airMonthpickerInput (airDatepicker), 8
airYearpickerInput (airDatepicker), 8
animateOptions, 11, 29
animations, 12, 12
awesomeCheckbox, 13, 92
awesomeCheckboxGroup, 14, 94
awesomeRadio, 15, 95
checkboxGroupButtons, 17, 97
checkboxGroupInput, 17
chooseSliderSkin, 18, 82
circleButton, 20
closeSweetAlert, 20
colorSelectorDrop (colorSelectorInput),
21
colorSelectorExample
(colorSelectorInput), 21
colorSelectorInput, 21
confirmSweetAlert, 22, 33, 74, 133
radioButtons, 69
radioGroupButtons, 69
searchInput, 70
selectizeGroup-module, 71
selectizeGroupServer
(selectizeGroup-module), 71
selectizeGroupUI
(selectizeGroup-module), 71
sendSweetAlert, 23, 33, 73, 133
setBackgroundColor, 76
setBackgroundImage, 78
setShadow, 79
setSliderColor, 19, 81
shinyWidgets, 83
shinyWidgets-package (shinyWidgets), 83
shinyWidgetsGallery, 83
sliderInput, 84
sliderTextInput, 84, 118
spectrumInput, 85
switchInput, 36, 87, 121
demoAirDatepicker, 10, 25
demoNoUiSlider, 26, 40
downloadBttn, 4, 27
dropdown, 28, 31
dropdownButton, 30
icon, 89
inputSweetAlert, 23, 32, 74, 133
knobInput, 33
materialSwitch, 35, 88, 101
multiInput, 36, 102
textInputAddon, 88
137138
timepickerOptions, 9
timepickerOptions (airDatepicker), 8
toggleDropdownButton, 31, 89
tooltipOptions, 29, 91
updateAirDateInput, 10, 91
updateAwesomeCheckbox, 13, 92
updateAwesomeCheckboxGroup, 14, 93
updateAwesomeRadio, 16, 95
updateCheckboxGroupButtons, 18, 97
updateKnobInput, 34, 99
updateMaterialSwitch, 36, 101
updateMultiInput, 37, 102
updateNoUiSliderInput, 40, 103
updatePickerInput, 45, 104
updatePrettyCheckbox, 52, 106
updatePrettyCheckboxGroup, 56, 107
updatePrettyRadioButtons, 109
updatePrettySwitch, 60, 111
updatePrettyToggle, 63, 113
updateProgressBar (progress-bar), 65
updateRadioGroupButtons, 114
updateSearchInput, 71, 116
updateSliderTextInput, 85, 117
updateSpectrumInput, 119
updateSwitchInput, 88, 120
updateVerticalTabsetPanel, 125, 133
useShinydashboard, 126
useShinydashboardPlus, 128
useSweetAlert, 132
vertical-tab, 133
verticalTabPanel (vertical-tab), 133
verticalTabsetPanel, 125
verticalTabsetPanel (vertical-tab), 133
wNumbFormat, 39, 134
INDEX
