
---
title: "``shinyWidgets::dropdownButton``"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ``dropdownButton``
Dropdown Button

#### Description

Create a dropdown menu with Bootstrap where you can put input elements.

#### Usage
<pre><code>

dropdownButton(..., circle = TRUE, status = "default",
size = "default", icon = NULL, label = NULL, tooltip = FALSE,
right = FALSE, up = FALSE, width = NULL, inputId = NULL)

</code></pre>
#### Arguments

* ``size ``:  Size of the button : default, lg, sm, xs.
* icon An icon to appear on the button.
* ``label``: Label to appear on the button. If circle = TRUE and tooltip = TRUE, label is used in tooltip.
* ``tooltip``: Put a tooltip on the button, you can customize tooltip with tooltipOptions.
* ``right``: Logical. The dropdown menu starts on the right.
* ``up``: Logical. Display the dropdown menu above.
* ``width``: Width of the dropdown menu content.
* ``inputId``: Optional, id for the button, the button act like an actionButton, and you can use the id to toggle the dropdown menu server-side with toggleDropdownButton.


#### Examples
<pre><code>

## Only run examples in interactive R sessions
if (interactive()) {
library(shiny)
library(shinyWidgets)
ui <- fluidPage(
dropdownButton(
inputId = "mydropdown",
label = "Controls",
icon = icon("sliders"),
status = "primary",
circle = FALSE,
sliderInput(
inputId = "n",
label = "Number of observations",
min = 10, max = 100, value = 30
),
prettyToggle(
inputId = "na",
label_on = "NAs keeped",
label_off = "NAs removed",
icon_on = icon("check"),
icon_off = icon("remove")
)
),
)
tags$div(style = "height: 140px;"), # spacing
verbatimTextOutput(outputId = "out"),
verbatimTextOutput(outputId = "state")
server <- function(input, output, session) {
output$out <- renderPrint({
cat(
" # n\n", input$n, "\n",
"# na\n", input$na
)
})
output$state <- renderPrint({
cat("Open:", input$mydropdown_state)
})
}
shinyApp(ui, server)
}
## End(Not run)
</code></pre>


#### Details
It is possible to know if a dropdown is open or closed server-side with input$<inputId>_state.
Note
pickerInput doesn’t work inside dropdownButton because that’s also a dropdown and you can’t
nest them. Instead use dropdown, it has similar features but is built differently so it works.
