---
title: "``shinyWidgets::panel``"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Create a panel

#### Description

Create a panel (box) with basic border and padding, you can use Bootstrap status to style the panel,
see http://getbootstrap.com/components/#panels.

#### Usage
<pre><code>

panel(..., heading = NULL, footer = NULL, status = "default")

</code></pre>
#### Arguments

* ``...``: UI elements to include inside the panel.
* ``heading``: Title for the panel in a plain header.
* ``footer``: Footer for the panel.
* ``status``: Bootstrap status for contextual alternative.

#### Value

A UI definition.

#### Examples
<pre><code>

library("shiny")
library("shinyWidgets")
ui <- fluidPage(
  # Default
  panel(42
        pickerGroup-module
        "Content goes here",
        checkboxInput(inputId = "id1", label = "Label")
  ),
  # With header and footer
  panel(
    "Content goes here",
    checkboxInput(inputId = "id2", label = "Label"),
    heading = "My title",
    footer = "Something"
  ),
)
# With status
panel(
  "Content goes here",
  checkboxInput(inputId = "id3", label = "Label"),
  heading = "My title",
  status = "primary"
)
server <- function(input, output, session) {
}
shinyApp(ui = ui, server = server)

</code></pre>
